### ISSUE TITLE
Supported TFS versions?

### ISSUE THREAD

**Issue by NenoLoje** [Microsoft/vsts-jboss-wildfly#5]
What versions of TFS are supported by this extension? Is TFS 2015.3 supported?

--Neno

**Comment by yacaovsnc** [comment]
Unfortunately the service endpoint type isn't supported in TFS 2015.3 at the moment.  We will explore some options and add support of TFS 2015.3.  I will keep you posted.  

Thanks for your patience.

**Comment by NenoLoje** [comment]
Thanks, Yang!

**Comment by yacaovsnc** [comment]
@NenoLoje thanks for your patience.  Would you mind giving this [new release](https://github.com/Microsoft/vsts-jboss-wildfly/releases/tag/0.112.0) a try and see if it works with your TFS 2015.3 server?

Thanks.

**Comment by NenoLoje** [comment]
Yang, in TFS 2015.3 I don't see a service endpoint called "JBoss and WildFly". Is that expected?

Thanks,
--Neno

**Comment by yacaovsnc** [comment]
Yes, since TFS 2015 doesn't support service endpoint extensibility framework.  We added a dropdown in the task to allow you to enter credentials manually.  

Thanks for your help!

**Comment by yacaovsnc** [comment]
TFS 2015 support is in and released to market place.  Thanks for your help!

**Comment by NenoLoje** [comment]
I can confirm that entering credentials manually works now in TFS 2015. Thanks, Yang!
