### ISSUE TITLE
TFS2015 UPD1 - "Extension manifest file format is invalid" when installation extension

### ISSUE THREAD

**Issue by spashx** [Microsoft/vsts-jboss-wildfly#7]
I tried to install it on a TFS 2015 UPD1 instance. I get "Extension manifest file format is invalid".
The downloaded file is ms-vsts.jboss-wildfly-management-extension-0.112.1.vsix
It is assumed to work on TFS2015 UPD1 ? The documentation does not specify the supported version.
Thanks.

**Comment by yacaovsnc** [comment]
https://www.visualstudio.com/en-us/news/releasenotes/tfs2015-update2-vs#suppext

Extension support is introduced in TFS 2015.2.  

Sorry for the delayed response.  I was on vacation back then and must have missed the email notification.  :(
